name: MinecraftHistory
version: '${project.version}'
main: main.MinecraftHistory
api-version: 1.19
authors: [ Awesome_Chicken ]
description: a plugin to help you learn about history!
commands:
  menu:
    description: 'The command to open the main menu'